import { type NextRequest, NextResponse } from "next/server"
import { sendEmail } from "@/lib/email-sender"
import { getMeetingSummary } from "@/lib/db"

export async function POST(request: NextRequest) {
  try {
    const { meetingId, userId } = await request.json()

    if (!meetingId || !userId) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    // Fetch meeting summary from database
    let summary: any
    try {
      const dbSummary = await getMeetingSummary(meetingId, userId)
      if (!dbSummary || dbSummary.length === 0) {
        return NextResponse.json({ error: "Meeting summary not found" }, { status: 404 })
      }
      
      const m = dbSummary[0]
      summary = {
        title: m.title,
        keyTakeaways: m.key_takeaways || [],
        actionItems: m.action_items || [],
        decisions: m.decisions || [],
        unresolvedTopics: m.unresolved_topics || [],
        insights: m.insights || {
          mostDiscussedTopic: "General Discussion",
          sentiment: "neutral",
          duration: 0,
          participantCount: 0,
        },
      }
    } catch (error: any) {
      console.warn("[API] DB unavailable, using mock data:", error?.message)
      // Fallback to mock data
      summary = {
        title: "Team Standup Meeting",
        keyTakeaways: ["Project on track", "Frontend completed"],
        actionItems: ["Review designs", "Update timeline"],
        decisions: ["Use blue-green deployment"],
        unresolvedTopics: ["Budget allocation"],
        insights: {
          mostDiscussedTopic: "Timeline",
          sentiment: "positive",
          duration: 1800,
          participantCount: 4,
        },
      }
    }

    // Format email content
    const emailContent = `
Meeting Summary: ${summary.title}

✅ Key Takeaways:
${summary.keyTakeaways.map(item => `• ${item}`).join('\n')}

📋 Action Items:
${summary.actionItems.map(item => `• ${item}`).join('\n')}

💬 Decisions Made:
${summary.decisions.map(item => `• ${item}`).join('\n')}

${summary.unresolvedTopics.length > 0 ? `❗ Unresolved Topics:\n${summary.unresolvedTopics.map(item => `• ${item}`).join('\n')}` : ''}

📊 Insights:
• Most Discussed: ${summary.insights.mostDiscussedTopic}
• Sentiment: ${summary.insights.sentiment}
• Duration: ${Math.floor(summary.insights.duration / 60)} minutes
• Participants: ${summary.insights.participantCount}

---
Generated by AI Heir Meeting Assistant
    `.trim()

    // Get user email (mock for demo)
    const userEmail = "user@example.com" // In production: await getUserEmail(userId)

    try {
      await sendEmail({
        to: userEmail,
        subject: `Meeting Summary: ${summary.title}`,
        text: emailContent,
      })

      return NextResponse.json({
        success: true,
        message: "Email sent successfully",
      })
    } catch (error: any) {
      console.error("[API] Email send error:", error)
      return NextResponse.json({ error: "Failed to send email", details: error.message }, { status: 500 })
    }
  } catch (error: any) {
    console.error("[API] Send email error:", error)
    return NextResponse.json({ error: "Failed to process request" }, { status: 500 })
  }
}

